### PR TITLE
Redo the raft autojoin

### PR DESCRIPTION
**Pull request by Bluekind1**
Raft autojoin endpoint changed to vault-active service to make the Vault pods join the cluster automatically.

### CODE REVIEW

**Comment by in0rdr** [comment]
Thanks for the PR :raised_hands: 

Could you please read through https://github.com/hashicorp/vault/blob/main/website/content/docs/platform/k8s/helm/examples/ha-tls.mdx and elaborate on the problem that this PR attempts to fix? It would be helpful if you can post the concrete error message or output. Thanks a lot.

**Comment by Bluekind1** [comment]
Retested it again and this would've solved a non-issue

**Comment by Bluekind1** [comment]
Retested it again and this would've solved a non-issue

**Comment by in0rdr** [comment]
I get it, thanks for confirming that it is not an issue per se. However, since we have two options to configure the backend here according to the link above, I still think we should favor the option with less code.

What do you think @Xelef2000

**Comment by Bluekind1** [comment]
Closed for [PR 22](https://github.com/adfinis/vault-playground-on-kubernetes/pull/22)

**Pull request closed without merging**
